config/routes.rb
Chordination::Application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get "login" => "devise/sessions#new"
    delete "logout" => "devise/sessions#destroy"
    get "profile" => "devise/registrations#edit"
    get "register" => "devise/registrations#new"
    post "register" => "devise/registrations#create"
  end
  
  get "about" => "pages#about"
  get "dashboard" => "pages#dashboard"
  
  #entries
  get "entries/:key/new" => "entries#new"
  get "entries/:key" => "entries#show"
  get "entries/:key/edit" => "entries#edit"
  put "entries/:key" => "entries#update"
  post "entries/:key/accept" => "entries#accept"
  delete "entries/:key/decline" => "entries#decline"
  post "entries/:key/message" => "entries#message"
      
  resources :scoresheets do
    member do
      get 'results' => "bets#results"
      put 'results' => "bets#save_results"
      get 'clone' => "scoresheets#new"
    end
    resources :bets do
      collection { post :sort }
    end
    resources :results
    resources :participants do
      collection { post :sort }
      member { get :reinvite }
    end
  end
  
  root :to => 'pages#home'
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  acts_as_list :scope => :scoresheet
  belongs_to :scoresheet, :inverse_of => :participants
  has_many :bets, :through => :scoresheet, order: 'bets.position'
  has_many :entries, :dependent => :destroy, autosave: true, :include => :bet, order: 'bets.position'
  has_many :messages, autosave: true, order: 'messages.created_at'
  
  scope :accepted, where(accepted: true)
  scope :declined, where(declined: true)
  
  attr_accessible :name, :email, :entries_attributes, :accepted, :declined
  
  accepts_nested_attributes_for :entries
  
  validates :name, :email, :scoresheet, :key, presence: true
  validates :email, uniqueness: {:scope => :scoresheet_id}
  validates :name, uniqueness: {:scope => :scoresheet_id}
  validates :key, uniqueness: true
  
  #assign unique random key
  before_validation(:on => :create) do
    self.key = loop do
      random_key = SecureRandom.urlsafe_base64
      break random_key unless Participant.where(key: random_key).exists?
    end
  end
    
  def build_entry_fields
    self.bets.each do |b|
      self.entries.build(bet_id: b.id) unless self.entries.map(&:bet_id).include?(b.id)
    end
  end
    
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:scoresheet_id])
    @participant = Participant.new
  end
  
  def create
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:scoresheet_id])
    @participant = Participant.new(params[:participant])
    @participant.scoresheet_id = params[:scoresheet_id]
    if @participant.save
      ParticipantMailer.invitation_email(@participant).deliver
      redirect_to @scoresheet, notice: 'Successfully added participant.'
    else
      render :new
    end    
  end
  
  def edit
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:scoresheet_id])
    @participant = Participant.find(params[:id])
  end
  
  def update
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:scoresheet_id])
    @participant = Participant.find(params[:id])
    if ["move_lower", "move_higher"].include? params[:method]
      @participant.send params[:method]
      redirect_to scoresheet_path(params[:scoresheet_id])
    else
      if @participant.update_attributes(params[:participant])
        redirect_to @scoresheet, notice: 'Successfully updated participant.'
      else
        render :edit
      end
    end
  end
  
  def destroy
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:scoresheet_id])
    @participant = Participant.find(params[:id])
    @participant.destroy
    redirect_to @scoresheet, notice: "#{@participant.name} has successfully been removed."
  end
  
  def reinvite
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:scoresheet_id])
    @participant = Participant.find(params[:id])
    @participant.update_attributes(declined: false) if @participant.declined? #reset declined flag
    ParticipantMailer.invitation_email(@participant).deliver
    redirect_to @scoresheet, notice: "Successfully re-invited #{@participant.email}."
  end
  
  def sort
    params[:participant].each_with_index do |id, index|
      Participant.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= render 'layouts/errors', object: @participant %>
<%= form_for [@scoresheet, @participant], html: { autocomplete: 'off', class: 'form-horizontal'} do |f| %>
  <fieldset>
    <div id="legend">
      <legend class="">Participant</legend>
    </div>
    
    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, autofocus: true, class: 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :email, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, class: 'input-xlarge' %>
      </div>
    </div>
    <div class="control-group">
      <!-- Button -->
      <div class="controls">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/participants/edit.html.erb
<%= render 'form' %>

app/views/participants/edit_entries.html.erb
<h2><%= @participant.name %>'s Entries</h2>
<%= form_for @participant, url: participant_path(@participant.key), html: { class: 'form-horizontal'} do |f| %>
  <table class="table table-striped table-hover table-condensed">
    <%= f.fields_for :entries do |e| %>
      <tr>
        <td><%= e.object.bet.name %></td>
        <td>
          <%= e.hidden_field :bet_id %>
          <%= e.hidden_field :participant_id %>
          <%= e.text_field :value %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= f.submit 'Submit', class: 'btn btn-success' %>
<% end %>

app/views/participants/new.html.erb
<%= render 'form' %>