config/routes.rb
Chordination::Application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get "login" => "devise/sessions#new"
    delete "logout" => "devise/sessions#destroy"
    get "profile" => "devise/registrations#edit"
    get "register" => "devise/registrations#new"
    post "register" => "devise/registrations#create"
  end
  
  get "about" => "pages#about"
  get "dashboard" => "pages#dashboard"
  
  #entries
  get "entries/:key/new" => "entries#new"
  get "entries/:key" => "entries#show"
  get "entries/:key/edit" => "entries#edit"
  put "entries/:key" => "entries#update"
  post "entries/:key/accept" => "entries#accept"
  delete "entries/:key/decline" => "entries#decline"
  post "entries/:key/message" => "entries#message"
      
  resources :scoresheets do
    member do
      get 'results' => "bets#results"
      put 'results' => "bets#save_results"
      get 'clone' => "scoresheets#new"
    end
    resources :bets do
      collection { post :sort }
    end
    resources :results
    resources :participants do
      collection { post :sort }
      member { get :reinvite }
    end
  end
  
  root :to => 'pages#home'
end

app/models/scoresheet.rb
class Scoresheet < ActiveRecord::Base
  belongs_to :user
  has_many :bets, :dependent => :destroy, autosave: true, :inverse_of => :scoresheet, order: 'bets.position'
  has_many :participants, :dependent => :destroy, autosave: true, :inverse_of => :scoresheet, order: 'participants.position'
  has_many :messages, :dependent => :destroy, autosave: true, order: 'messages.created_at'
  
  attr_accessible :name, :deadline, :message, :bets_attributes, :consolation, :consolation_points
  
  accepts_nested_attributes_for :bets
  
  scope :by_user, lambda { |id| where(user_id: id) }
  
  validates_presence_of :user_id, :name, :deadline
  validates_uniqueness_of :name, :scope => :user_id
  
  def participant_count
    self.participants.length
  end
  
  def expired?
    self.deadline < Time.now
  end
  
  def results_in?
    !self.bets.map(&:value).any? {|i| i.nil? }
  end
  
  def build_result_fields
    self.bets.each {|b| self.bets.build unless self.bets.map(&:id).include?(b.id)}
  end
  
  def clone_from(id)
    original = Scoresheet.by_user(self.user_id).find(id)
    original.bets.order("position").each do |b|
      self.bets.build(name: b.name, bet_type: b.bet_type, choices: b.choices, points: b.points)
    end
    original.participants.order("position").each do |p|
      self.participants.build(name: p.name, email: p.email)
    end
  end
  
  def compile_entries(results=nil)
    #initialize hash by bet id
    entries = {}
    self.bets.each do |b|
      entries[b.id] = {}
      
      #add results if results are in
      entries[b.id]['result'] = (b.bet_type == "winner" ? "#{b.winner} by #{b.value}" : b.value) if results
    end
    
    #populate
    self.participants.accepted.each do |p|
      p.entries.each do |e|      
        entries[e.bet_id][p.name] = (e.bet.bet_type == 'winner' ? "#{e.winner} by #{e.value}" : e.value)
      end
    end
    
    entries    
  end
  
  def compile_differentials
    #initialize hash by bet_id
    differentials = {}
    self.bets.each {|b| differentials[b.id] = {}}
    
    #populate
    self.participants.accepted.each do |p|
      p.entries.each do |e|
        entry = e.value.to_i
        result = e.bet.value.to_i if e.bet.value.present?
        if result
          differentials[e.bet_id][p.name] = if e.bet.bet_type == 'winner' && e.bet.winner != e.winner
            #if you picked the wrong winner
            entry + result
          else
            (result - entry).abs
          end
        end
      end
    end
    
    differentials    
  end
  
  def compile_consolation(differentials={})
    consolation = {}
    if self.consolation?
      self.participants.accepted.each do |p|
        consolation[p.name] = 0
        non_winner_bet_types = self.bets.select {|b| b.bet_type != 'winner'}
        winner_bet_types = self.bets.select{|b| b.bet_type == 'winner'}
        
        non_winner_bet_types.each do |b|
          consolation[p.name] += differentials[b.id][p.name]
        end
        
        winner_bet_types.each do |b|
          consolation[p.name] += differentials[b.id][p.name]
          consolation[p.name] -= 3 if b.winner == p.entries.detect {|e| e.bet_id == b.id}.try(:winner) #3 pt discount if winner picked correctly
        end
      end
    end
    
    consolation
  end
  
  def compile_winners(differentials, entries, consolation={})
    def tiebreaker(bet, entries, winners)
      tiebreak = []
      winners.each do |w|
        if entries[bet.id][w].split(" by ").first == bet.winner
          tiebreak << w
        end
      end
      
      tiebreak
    end
    
    winners = {}
    self.bets.each do |b|
      lowest_diff = differentials[b.id].values.sort.first
      bet_winner = differentials[b.id].select {|k,v| v == lowest_diff}.keys
      if b.bet_type == 'winner' && bet_winner.length > 1 #break the tie by who picked correct winner
        winners[b.id] = tiebreaker(b, entries, bet_winner)
      else
        winners[b.id] = bet_winner
      end
    end
    
    #add consolation winner
    if self.consolation? && consolation.present?
      lowest_consolation = consolation.values.sort.first
      winners['consolation'] = consolation.select {|k,v| v == lowest_consolation}.keys
    end
    
    winners
  end
  
  def compile_standings(winners)
    standings = {}
    participants = self.participants.accepted
    participants_count = participants.length
    
    #populate
    participants.each do |p|
      standings[p.name] = {}    
      self.bets.each do |b|
        winner_count = winners[b.id].length
        loser_count = (participants_count - winner_count)
        standings[p.name][b.id] = (winners[b.id].include?(p.name) ? loser_count * b.points.to_f / winner_count.to_f : b.points*-1)
      end
      
      #add consolation standing
      if self.consolation?
        consolation_winner_count = winners['consolation'].length
        consolation_loser_count = (participants_count - consolation_winner_count)        
        standings[p.name]['consolation'] = (winners['consolation'].include?(p.name) ? consolation_loser_count * self.consolation_points / consolation_winner_count : self.consolation_points*-1)
      end
    end
    
    standings
  end

end

app/controllers/scoresheets_controller.rb
class ScoresheetsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @scoresheets = Scoresheet.by_user(current_user.id).order("deadline DESC")
  end
  
  def new
    @scoresheet = Scoresheet.new
    @original = Scoresheet.by_user(current_user.id).find_by_id(params[:id])
  end
  
  def create
    @scoresheet = Scoresheet.new(params[:scoresheet])
    @scoresheet.user_id = current_user.id
    @scoresheet.clone_from(params[:id]) if params[:id].present?
    if @scoresheet.save
      
      #add creator as participant if not already
      unless @scoresheet.participants.exists?(name: current_user.name)
        @scoresheet.participants.create(name: current_user.name, email: current_user.email, accepted: true)
      end
      
      @scoresheet.participants.each {|p| ParticipantMailer.invitation_email(p).deliver} #send invites
      redirect_to @scoresheet, notice: 'Scoresheet successfully created.'
    else
      @original = Scoresheet.by_user(current_user.id).find_by_id(params[:id])
      render :new
    end
  end
  
  def edit
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:id])
  end
  
  def update
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:id])
    if @scoresheet.update_attributes(params[:scoresheet])
      redirect_to scoresheet_path(@scoresheet), notice: 'Scoresheet successfully updated.'
    else
      render :edit
    end
  end
    
  def show
    @scoresheet = Scoresheet.by_user(current_user.id).find(params[:id])
  end
    
  def destroy
  end
  
end

app/helpers/scoresheets_helper.rb
module ScoresheetsHelper
end

app/views/scoresheets/_bets.html.erb
<h3>Bets</h3>
<table id="bets" class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Wager</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody data-update-url="<%= sort_scoresheet_bets_path(@scoresheet) %>">
    <% @scoresheet.bets.each do |b| %>
      <%= content_tag_for(:tr, b) do %>
        <td><%= b.name %></td>
        <td><%= b.bet_type %></td>
        <td><%= pluralize(b.points, 'pt') %></td>
        <td class="icon_button"><%= link_to("", edit_scoresheet_bet_path(@scoresheet, b), class: 'icon-pencil btn') %></td>
        <td class="icon_button"><%= link_to("", [@scoresheet, b], :method => :delete, class: 'icon-trash btn btn-danger', data: { confirm: "Are you sure you want to remove \"#{b.name}\"?"}) %></td>
      <% end %>
    <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'Add Bet', new_scoresheet_bet_path(@scoresheet), class: 'btn btn-success' %>
  <% if you = @scoresheet.participants.detect {|i| i.email == current_user.email } %>
    <%= link_to 'Your Entries', "/entries/#{you.key}", target: '_blank', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Results', results_scoresheet_path(@scoresheet), class: 'btn btn-inverse'%>
</p>

app/views/scoresheets/_form.html.erb
<%= render 'layouts/errors', object: @scoresheet %>
<%= form_for @scoresheet, html: { autocomplete: 'off', class: 'form-horizontal' } do |f| %>
  <%= hidden_field_tag :id, params[:id] %>
  <fieldset>
    <div id="legend">
      <legend class="">Scoresheet</legend>
    </div>
    
    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, autofocus: true, class: 'input-xlarge' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :deadline, class: 'control-label' %>
      <div class="controls">
        <%= f.datetime_select :deadline %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :message, class: 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, rows: 5, class: 'span6' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :consolation, 'Consolation Bet?', class: 'control-label' %>
      <div class="controls">
        <%= f.check_box :consolation %>
      </div>
    </div>
    
    <div class="control-group consolation-points">
      <%= f.label :consolation_points, 'Consolation Points', class: 'control-label' %>
      <div class="controls">
        <%= f.number_field :consolation_points, autofocus: true, class: 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <!-- Button -->
      <div class="controls">
        <% if @original %>
          <%= f.submit "Clone #{@original.name}", class: 'btn btn-success' %>
        <% else %>
          <%= f.submit class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/scoresheets/_participants.html.erb
<h3>Participants</h3>
<table id="participants" class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody data-update-url="<%= sort_scoresheet_participants_path(@scoresheet) %>">
    <% @scoresheet.participants.each do |p| %>
      <%= content_tag_for(:tr, p) do %>
        <td><%= p.name %></td>
        <td><%= p.email %></td>
        <td><%= status?(p) %></td>
        <td><%= link_to "Resend Invite", reinvite_scoresheet_participant_path(@scoresheet, p), class: 'btn btn-info' %></td>
        <td class="icon_button"><%= link_to "", edit_scoresheet_participant_path(@scoresheet, p), class: 'icon-pencil btn' %></td>
        <td class="icon_button"><%= link_to "", [@scoresheet, p], :method => :delete, class: 'icon-trash btn btn-danger', data: { confirm: "Are you sure you want to remove #{p.name}?"} %></td>
      <% end %>
    <% end %>
  </tbody>
</table>
<p><%= link_to 'Add Participant', new_scoresheet_participant_path(@scoresheet), class: 'btn btn-success' %></p>

app/views/scoresheets/edit.html.erb
<%= render 'form' %>

app/views/scoresheets/index.html.erb
<h2>Scoresheets</h2>

<p><%= link_to 'Add', new_scoresheet_path, class: 'btn' %></p>
<table class="table table-striped table-hover table-condensed">
  <tr>
    <th>Name</th>
    <th>Deadline</th>
    <th>Participants</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>
  <% @scoresheets.each do |i| %>
    <tr>
      <td><%= i.name %></td>
      <td><%= pretty_datetime(i.deadline) %></td>
      <td><%= i.participant_count %>
      <td><%= pretty_datetime(i.created_at) %></td>
      <td><%= pretty_datetime(i.updated_at) %></td>
      <td><%= link_to 'Clone', clone_scoresheet_path(i), class: 'btn btn-info' %>
      <td><%= link_to 'View', scoresheet_path(i), class: 'btn' %>
    </tr>
  <% end %>
</table>

app/views/scoresheets/new.html.erb
<%= render 'form' %>

app/views/scoresheets/show.html.erb
<h2><%= @scoresheet.name %> <%= link_to "", edit_scoresheet_path(@scoresheet), class: 'icon-pencil btn'%></h2>
<h3>Deadline: <%= pretty_datetime(@scoresheet.deadline, ampm: true) %></h3>
<div class="well"><%= render 'bets' %></div>
<div class="well"><%= render 'participants' %></div>