config/routes.rb
Chordination::Application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get "login" => "devise/sessions#new"
    delete "logout" => "devise/sessions#destroy"
    get "profile" => "devise/registrations#edit"
    get "register" => "devise/registrations#new"
    post "register" => "devise/registrations#create"
  end
  
  get "about" => "pages#about"
  get "dashboard" => "pages#dashboard"
  
  #entries
  get "entries/:key/new" => "entries#new"
  get "entries/:key" => "entries#show"
  get "entries/:key/edit" => "entries#edit"
  put "entries/:key" => "entries#update"
  post "entries/:key/accept" => "entries#accept"
  delete "entries/:key/decline" => "entries#decline"
  post "entries/:key/message" => "entries#message"
      
  resources :scoresheets do
    member do
      get 'results' => "bets#results"
      put 'results' => "bets#save_results"
      get 'clone' => "scoresheets#new"
    end
    resources :bets do
      collection { post :sort }
    end
    resources :results
    resources :participants do
      collection { post :sort }
      member { get :reinvite }
    end
  end
  
  root :to => 'pages#home'
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">&#215;</a>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chordination</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Chordination', root_path, class: 'brand' %>
        <% if @participant %>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="<%= 'active' if controller_name == 'entries' %>"><%= link_to 'Entries', "/entries/#{@participant.key}" %></li>
            </ul>
          </div>
          <div class="pull-right">
            <span style="color: white;">
              <h4><%= @participant.name %></h4>
            </span>
          </div>          
        <% else %>
          <div class="nav-collapse">
            <ul class="nav">
              <% if current_user %>
                <li class="<%= 'active' if controller_name == 'scoresheets' %>"><%= link_to 'Scoresheets', scoresheets_path %></li>
                <li class="<%= 'active' if request.fullpath == '/profile' %>"><%= link_to 'Profile', profile_path %></li>
              <% else %>
                <li class="<%= 'active' if controller_name == 'registrations' %>"><%= link_to 'Register', register_path %></li>
              <% end %>
              <li class="<%= 'active' if action_name == 'about' %>"><%= link_to 'About', '/about' %></li>
            </ul>
            <div class="pull-right">
              <% if current_user %>
                <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: 'btn btn-danger' %>
              <% else %>
                <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <%= msg %>
      </div>
    <% end %>
    <div class="row">
      <div class="span12"><%= yield %></div>
    </div>
  </div>
  <hr>
  <footer class="footer">
    <div class="container">
      <p><%= Rails.application.config.copyright %></p>
    </div>
  </footer>
</body>
</html>